version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: ~/tmp
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install packages
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Start Building the App
          command: yarn run build


workflows:
  build-for-test:
    jobs:
      - build
