version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
      - run:
          name: Start Building the App
          command: yarn run build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy GitHub Page
          command: yarn run deploy

workflows:
  build-for-test:
    jobs:
      - build:
        filters:
          branches:
            ignore: master
  build-for-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: master
      - deploy:
          requires:
            - build
